#cloud-config
users:
  - name: ${vm_user}
    primary_group: ${vm_user}
    groups: sudo, wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:${vm_user}
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_key}

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - qemu-guest-agent
  - nfs-common
  - tmux
  - bwm-ng
  - tcpdump
  - net-tools
  - git
  - curl
  - jq
  - mosh

write_files:
- path: /usr/local/etc/k0s.yaml
  permissions: '0644'
  content: |
    spec:
      extensions:
        storage:
          type: openebs_local_storage

- path: /usr/local/etc/install_k0s.sh
  permissions: '0755'
  content: |
    #!/usr/bin/env bash
    echo "download and install k0s ..."
    curl -sSLf https://get.k0s.sh | K0S_VERSION=v1.23.15+k0s.0 sh
    chmod +x /usr/local/bin/k0s
    ln -s /usr/local/bin/k0s /usr/local/bin/kubectl
    mount 192.168.40.2:/opt/nfs_shared_folder /mnt/
    until test -e /mnt/${cluster_name}-worker.token; do echo "waiting for k0s worker token ..." && sleep 5; done
    cp /mnt/${cluster_name}-worker.token /usr/local/etc/
    umount /mnt/
    /usr/local/bin/k0s install worker --token-file /usr/local/etc/${cluster_name}-worker.token
    /usr/local/bin/k0s start  

bootcmd:
  - echo "vm.nr_hugepages=400" >> /etc/sysctl.conf
  - hostname ${host-name}

runcmd:
  - /usr/local/etc/install_k0s.sh

hostname: ${host-name}
fqdn: ${host-name}

